remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
title: Snort3 Install Guide
description: This is a simple guide for snort3 that I think is a little better than the official one.
show_downloads: false
